workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: Styloria ASC
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.styloria.app
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
        GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Create .env file
        script: |
          echo "STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY" > .env
          echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> .env
      
      - name: Set up iOS Google Maps API Key
        script: |
          if [ -f "ios/Runner/AppDelegate.swift" ]; then
            sed -i '' "s/GOOGLE_MAPS_API_KEY_PLACEHOLDER/$GOOGLE_MAPS_API_KEY/g" ios/Runner/AppDelegate.swift || true
          fi
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true