workflows:
  default-workflow:
    name: Styloria Mobile Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
        GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    
    scripts:
      - name: Create .env file
        script: |
          echo "STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY" > .env
          echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> .env
          echo "Created .env file:"
          cat .env

      - name: Set up iOS Google Maps API Key
        script: |
          sed -i '' "s/GOOGLE_MAPS_API_KEY_PLACEHOLDER/$GOOGLE_MAPS_API_KEY/g" ios/Runner/AppDelegate.swift
      
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Install CocoaPods
        script: cd ios && pod install
      
      - name: Build Android Debug APK
        script: flutter build apk --debug
      
      - name: Build iOS Simulator
        script: flutter build ios --debug --simulator
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphonesimulator/**/*.app