workflows:
  android-ios-workflow:
    name: Android & iOS Build
    max_build_duration: 60
    
    environment:
      flutter: stable
      vars:
        GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    
    scripts:
      - name: Set up iOS Google Maps API Key
        script: |
          sed -i '' "s/GOOGLE_MAPS_API_KEY_PLACEHOLDER/$GOOGLE_MAPS_API_KEY/g" ios/Runner/AppDelegate.swift
      
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Build Android APK
        script: flutter build apk --debug
      
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa