// lib/utils/country_city_data.dart

class CountryCityData {
  // All countries with their major cities
  static final Map<String, List<String>> countriesWithCities = {
    // West African Countries
    'Ghana': [
      'Accra',
      'Kumasi',
      'Tamale',
      'Sekondi-Takoradi',
      'Ashaiman',
      'Sunyani',
      'Cape Coast',
      'Obuasi',
      'Teshie',
      'Tema',
      'Madina',
      'Koforidua',
      'Wa',
      'Ho',
      'Nungua',
      'Bawku',
      'Aflao',
      'Agona Swedru',
      'Bolgatanga',
      'Tarkwa',
    ],
    'Nigeria': [
      'Lagos',
      'Abuja',
      'Kano',
      'Ibadan',
      'Port Harcourt',
      'Benin City',
      'Maiduguri',
      'Zaria',
      'Aba',
      'Jos',
      'Ilorin',
      'Oyo',
      'Enugu',
      'Abeokuta',
      'Onitsha',
      'Warri',
      'Sokoto',
      'Calabar',
      'Akure',
      'Osogbo',
    ],
    'Côte d\'Ivoire': [
      'Abidjan',
      'Bouaké',
      'Daloa',
      'Yamoussoukro',
      'San-Pédro',
      'Divo',
      'Korhogo',
      'Anyama',
      'Abobo',
      'Man',
    ],
    'Senegal': [
      'Dakar',
      'Touba',
      'Thiès',
      'Rufisque',
      'Kaolack',
      'Mbour',
      'Ziguinchor',
      'Saint-Louis',
      'Diourbel',
      'Louga',
    ],
    'Mali': [
      'Bamako',
      'Sikasso',
      'Mopti',
      'Koutiala',
      'Ségou',
      'Kayes',
      'Kati',
      'Gao',
      'Markala',
      'Kolokani',
    ],
    'Burkina Faso': [
      'Ouagadougou',
      'Bobo-Dioulasso',
      'Koudougou',
      'Banfora',
      'Ouahigouya',
      'Dédougou',
      'Kaya',
      'Tenkodogo',
      'Fada N\'gourma',
      'Dori',
    ],
    'Niger': [
      'Niamey',
      'Zinder',
      'Maradi',
      'Agadez',
      'Almy',
      'Tahoua',
      'Dosso',
      'Birni Nkonni',
      'Tessaoua',
      'Gaya',
    ],
    'Guinea': [
      'Conakry',
      'Nzérékoré',
      'Kindia',
      'Boké',
      'Kankan',
      'Kissidougou',
      'Guéckédou',
      'Fria',
      'Mamou',
      'Macenta',
    ],
    'Benin': [
      'Cotonou',
      'Porto-Novo',
      'Parakou',
      'Djougou',
      'Bohicon',
      'Abomey',
      'Natitingou',
      'Lokossa',
      'Ouidah',
      'Savalou',
    ],
    'Togo': [
      'Lomé',
      'Sokodé',
      'Kara',
      'Kpalimé',
      'Atakpamé',
      'Bassar',
      'Tsévié',
      'Aného',
      'Mango',
      'Dapaong',
    ],
    'Liberia': [
      'Monrovia',
      'Gbarnga',
      'Buchanan',
      'Ganta',
      'Kakata',
      'Voinjama',
      'Zwedru',
      'Harper',
      'Robertsport',
      'Sanniquellie',
    ],
    'Sierra Leone': [
      'Freetown',
      'Bo',
      'Kenema',
      'Makeni',
      'Koidu',
      'Lunsar',
      'Port Loko',
      'Waterloo',
      'Kabala',
      'Segbwema',
    ],
    'Gambia': [
      'Banjul',
      'Serekunda',
      'Brikama',
      'Bakau',
      'Farafenni',
      'Lamin',
      'Sukuta',
      'Basse Santa Su',
      'Gunjur',
      'Soma',
    ],
    'Guinea-Bissau': [
      'Bissau',
      'Bafatá',
      'Gabú',
      'Bissorã',
      'Bolama',
      'Cacheu',
      'Bubaque',
      'Catió',
      'Mansôa',
      'Canchungo',
    ],
    'Cape Verde': [
      'Praia',
      'Mindelo',
      'Santa Maria',
      'Cova Figueira',
      'Santa Catarina',
      'Sal Rei',
      'Ponta do Sol',
      'Picos',
      'Assomada',
      'Tarrafal',
    ],
    'Mauritania': [
      'Nouakchott',
      'Nouadhibou',
      'Kaédi',
      'Kiffa',
      'Rosso',
      'Zouérat',
      'Atar',
      'Tidjikja',
      'Sélibaby',
      'Aleg',
    ],

    // Other African Countries
    'South Africa': [
      'Johannesburg',
      'Cape Town',
      'Durban',
      'Pretoria',
      'Port Elizabeth',
      'Bloemfontein',
      'East London',
      'Pietermaritzburg',
      'Kimberley',
      'Polokwane',
    ],
    'Kenya': [
      'Nairobi',
      'Mombasa',
      'Kisumu',
      'Nakuru',
      'Eldoret',
      'Thika',
      'Malindi',
      'Kitale',
      'Garissa',
      'Kakamega',
    ],
    'Ethiopia': [
      'Addis Ababa',
      'Dire Dawa',
      'Mekele',
      'Gondar',
      'Awasa',
      'Bahir Dar',
      'Dessie',
      'Jimma',
      'Jijiga',
      'Shashamane',
    ],
    'Tanzania': [
      'Dar es Salaam',
      'Mwanza',
      'Arusha',
      'Dodoma',
      'Mbeya',
      'Morogoro',
      'Tanga',
      'Kahama',
      'Tabora',
      'Zanzibar City',
    ],
    'Uganda': [
      'Kampala',
      'Gulu',
      'Lira',
      'Mbarara',
      'Jinja',
      'Bwizibwera',
      'Mbale',
      'Mukono',
      'Kasese',
      'Masaka',
    ],
    'Egypt': [
      'Cairo',
      'Alexandria',
      'Giza',
      'Shubra El-Kheima',
      'Port Said',
      'Suez',
      'Luxor',
      'Mansoura',
      'Tanta',
      'Asyut',
    ],
    'Morocco': [
      'Casablanca',
      'Rabat',
      'Fes',
      'Marrakesh',
      'Agadir',
      'Tangier',
      'Meknes',
      'Oujda',
      'Kenitra',
      'Tetouan',
    ],
    'Algeria': [
      'Algiers',
      'Oran',
      'Constantine',
      'Annaba',
      'Blida',
      'Batna',
      'Djelfa',
      'Setif',
      'Sidi Bel Abbes',
      'Biskra',
    ],
    'Cameroon': [
      'Douala',
      'Yaoundé',
      'Bamenda',
      'Bafoussam',
      'Garoua',
      'Maroua',
      'Ngaoundéré',
      'Kumba',
      'Buea',
      'Limbe',
    ],
    'Zambia': [
      'Lusaka',
      'Kitwe',
      'Ndola',
      'Kabwe',
      'Chingola',
      'Mufulira',
      'Livingstone',
      'Luanshya',
      'Chipata',
      'Kasama',
    ],
    'Zimbabwe': [
      'Harare',
      'Bulawayo',
      'Chitungwiza',
      'Mutare',
      'Gweru',
      'Kwekwe',
      'Kadoma',
      'Masvingo',
      'Chinhoyi',
      'Marondera',
    ],
    'Sudan': [
      'Khartoum',
      'Omdurman',
      'Port Sudan',
      'Kassala',
      'El Obeid',
      'Nyala',
      'Wad Medani',
      'El Fasher',
      'El Geneina',
      'Singa',
    ],

    // Western European Countries
    'United Kingdom': [
      'London',
      'Manchester',
      'Birmingham',
      'Glasgow',
      'Liverpool',
      'Bristol',
      'Leeds',
      'Edinburgh',
      'Sheffield',
      'Cardiff',
    ],
    'France': [
      'Paris',
      'Marseille',
      'Lyon',
      'Toulouse',
      'Nice',
      'Nantes',
      'Strasbourg',
      'Montpellier',
      'Bordeaux',
      'Lille',
    ],
    'Germany': [
      'Berlin',
      'Hamburg',
      'Munich',
      'Cologne',
      'Frankfurt',
      'Stuttgart',
      'Düsseldorf',
      'Dortmund',
      'Essen',
      'Leipzig',
    ],
    'Netherlands': [
      'Amsterdam',
      'Rotterdam',
      'The Hague',
      'Utrecht',
      'Eindhoven',
      'Tilburg',
      'Groningen',
      'Almere',
      'Breda',
      'Nijmegen',
    ],
    'Belgium': [
      'Brussels',
      'Antwerp',
      'Ghent',
      'Charleroi',
      'Liège',
      'Bruges',
      'Namur',
      'Leuven',
      'Mons',
      'Mechelen',
    ],
    'Spain': [
      'Madrid',
      'Barcelona',
      'Valencia',
      'Seville',
      'Zaragoza',
      'Málaga',
      'Murcia',
      'Palma',
      'Las Palmas',
      'Bilbao',
    ],
    'Italy': [
      'Rome',
      'Milan',
      'Naples',
      'Turin',
      'Palermo',
      'Genoa',
      'Bologna',
      'Florence',
      'Bari',
      'Catania',
    ],
    'Portugal': [
      'Lisbon',
      'Porto',
      'Vila Nova de Gaia',
      'Amadora',
      'Braga',
      'Funchal',
      'Coimbra',
      'Setúbal',
      'Almada',
      'Agualva-Cacém',
    ],
    'Switzerland': [
      'Zurich',
      'Geneva',
      'Basel',
      'Lausanne',
      'Bern',
      'Winterthur',
      'Lucerne',
      'St. Gallen',
      'Lugano',
      'Biel',
    ],
    'Ireland': [
      'Dublin',
      'Cork',
      'Limerick',
      'Galway',
      'Waterford',
      'Drogheda',
      'Dundalk',
      'Swords',
      'Bray',
      'Navan',
    ],
    'Austria': [
      'Vienna',
      'Graz',
      'Linz',
      'Salzburg',
      'Innsbruck',
      'Klagenfurt',
      'Villach',
      'Wels',
      'Sankt Pölten',
      'Dornbirn',
    ],
  };

  // Get sorted list of countries
  static List<String> get countries {
    final countryList = countriesWithCities.keys.toList();
    countryList.sort();
    return countryList;
  }

  // Get cities for a specific country
  static List<String> getCitiesForCountry(String country) {
    return countriesWithCities[country] ?? [];
  }

  // Check if a city exists in a country
  static bool isValidCityForCountry(String country, String city) {
    final cities = getCitiesForCountry(country);
    return cities.contains(city);
  }

  // Search cities by prefix
  static List<String> searchCities(String country, String query) {
    final cities = getCitiesForCountry(country);
    if (query.isEmpty) return cities;
    return cities
        .where((city) => city.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }
}